name: Links Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # repository_dispatch:
  # workflow_dispatch:
  # schedule:
  #   - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #- name: Fail if there were link errors
      #  run: exit ${{ steps.lychee.outputs.exit_code }}
        
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v2
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue

      - name: Save Report
        if: failure()
        run: |
          echo "## Broken Links Report" > broken_links_report.md
          grep "ERR" $GITHUB_WORKSPACE/.lychee.out >> broken_links_report.md
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: broken-links-report
          path: broken_links_report.md
